"""Regenerate contest-style standalone .cpp files using only Python stdlib."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
PROGRAMS = ('regex_to_nfa', 'nfa_to_dfa', 'dfa_minimize',
            'automaton_to_regex', 'regex_to_min_dfa', 'dfa_to_nfa')

def expand(path, seen):
    path = path.resolve()
    if path in seen:
        return ''
    seen.add(path)
    result = [f'// BEGIN {path.relative_to(ROOT).as_posix()}\n']
    for line in path.read_text(encoding='utf-8').splitlines(keepends=True):
        local = re.fullmatch(r'\s*#include\s+"([^"]+)"\s*', line)
        if local:
            result.append(expand(path.parent / local.group(1), seen))
        elif line.strip() != '#pragma once':
            result.append(line)
    result.append(f'\n// END {path.relative_to(ROOT).as_posix()}\n')
    return ''.join(result)

if __name__ == '__main__':
    target = ROOT / 'standalone'
    target.mkdir(exist_ok=True)
    for name in PROGRAMS:
        source = '// Generated by make_single.py; edit include/ and regenerate.\n'
        source += expand(ROOT / f'{name}.cpp', set())
        (target / f'{name}.cpp').write_text(source, encoding='utf-8')
    print(f'Generated {len(PROGRAMS)} standalone programs.')
