// Generated by make_single.py; edit include/ and regenerate.
// BEGIN dfa_minimize.cpp
// BEGIN include/cli.hpp
// BEGIN include/io.hpp
// BEGIN include/core.hpp
#include <algorithm>
#include <array>
#include <cstdint>
#include <deque>
#include <iostream>
#include <limits>
#include <numeric>
#include <queue>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace fa {
struct Edge { int to; int symbol; }; // symbol=-1: epsilon; otherwise alphabet index
struct NFA {
    int start = 0;
    std::vector<int> alphabet;
    std::vector<std::vector<Edge>> adj;
    std::vector<uint8_t> accept;
};
struct DFA {
    int start = 0;
    std::vector<int> alphabet;
    std::vector<std::vector<int>> trans; // -1 means implicit rejection
    std::vector<uint8_t> accept;
};
inline void require(bool ok, const std::string& message) {
    if (!ok) throw std::runtime_error(message);
}
inline void validate_alphabet(const std::vector<int>& alphabet) {
    std::array<bool,256> seen{};
    for (int c : alphabet) {
        require(c >= 0 && c < 256, "alphabet byte must be in [0,255]");
        require(!seen[c], "duplicate alphabet byte"); seen[c] = true;
    }
}
inline void validate(const NFA& a) {
    validate_alphabet(a.alphabet);
    require(!a.adj.empty() && a.adj.size() <= static_cast<size_t>(INT32_MAX), "invalid NFA state count");
    int n = static_cast<int>(a.adj.size()), k = static_cast<int>(a.alphabet.size());
    require(a.start >= 0 && a.start < n && a.accept.size() == a.adj.size(), "invalid NFA start/finals");
    for (int u=0; u<n; ++u) {
        require(a.accept[u] <= 1, "accept flags must be 0 or 1");
        for (auto e : a.adj[u]) require(e.to>=0 && e.to<n && e.symbol>=-1 && e.symbol<k, "invalid NFA edge");
    }
}
inline void validate(const DFA& a) {
    validate_alphabet(a.alphabet);
    require(!a.trans.empty() && a.trans.size() <= static_cast<size_t>(INT32_MAX), "invalid DFA state count");
    int n = static_cast<int>(a.trans.size());
    require(a.start>=0 && a.start<n && a.accept.size()==a.trans.size(), "invalid DFA start/finals");
    for (int u=0; u<n; ++u) {
        require(a.accept[u]<=1 && a.trans[u].size()==a.alphabet.size(), "invalid DFA row/final");
        for (int v : a.trans[u]) require(v>=-1 && v<n, "invalid DFA transition");
    }
}

// Reachable BFS, with a lazily created rejecting sink. Alphabet order is preserved.
inline DFA complete_reachable(const DFA& a) {
    validate(a);
    int n=static_cast<int>(a.trans.size()), k=static_cast<int>(a.alphabet.size());
    require(n<INT32_MAX, "too many DFA states to add a sink");
    std::vector<int> id(static_cast<size_t>(n)+1,-1), order{a.start};
    id[a.start]=0;
    DFA b; b.alphabet=a.alphabet;
    for (size_t i=0; i<order.size(); ++i) {
        int u=order[i];
        std::vector<int> row(k);
        for (int c=0;c<k;++c) {
            int v=(u==n || a.trans[u][c]<0) ? n : a.trans[u][c];
            if (id[v]<0) { id[v]=static_cast<int>(order.size()); order.push_back(v); }
            row[c]=id[v];
        }
        b.trans.push_back(std::move(row));
        b.accept.push_back(u==n ? 0 : a.accept[u]);
    }
    return b;
}
inline NFA as_nfa(const DFA& a) {
    validate(a);
    NFA b; b.start=a.start; b.alphabet=a.alphabet; b.accept=a.accept;
    b.adj.resize(a.trans.size());
    for (size_t u=0;u<a.trans.size();++u)
        for (size_t c=0;c<a.alphabet.size();++c)
            if (a.trans[u][c]>=0) b.adj[u].push_back({a.trans[u][c],static_cast<int>(c)});
    return b;
}

// Runtime-sized bitset: no fixed MAXN and no vector<bool> proxy overhead.
struct Bits {
    std::vector<uint64_t> w;
    Bits() = default;
    explicit Bits(size_t words) : w(words,0) {}
    void set(int i) { w[static_cast<size_t>(i)>>6] |= uint64_t(1)<<(i&63); }
    void merge(const Bits& b) { for(size_t i=0;i<w.size();++i) w[i]|=b.w[i]; }
    bool intersects(const Bits& b) const {
        for(size_t i=0;i<w.size();++i) if(w[i]&b.w[i]) return true;
        return false;
    }
    bool operator==(const Bits& b) const { return w==b.w; }
    template<class F> void each(F f) const {
        for(size_t i=0;i<w.size();++i) {
            uint64_t x=w[i];
            while(x) {
                unsigned bit=static_cast<unsigned>(__builtin_ctzll(x)); // x is nonzero
                f(static_cast<int>(i*64+bit)); x&=x-1;
            }
        }
    }
};
struct BitsHash {
    size_t operator()(const Bits& b) const noexcept {
        uint64_t h=0x243f6a8885a308d3ULL;
        for(uint64_t x : b.w) {
            x+=0x9e3779b97f4a7c15ULL; x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;
            x=(x^(x>>27))*0x94d049bb133111ebULL; x^=x>>31;
            h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);
        }
        return static_cast<size_t>(h);
    }
};
struct DeterminizeOptions {
    size_t max_states=200000;
    size_t max_bitset_bytes=268435456; // epsilon closures + subset keys + temporary words
    size_t max_cache_bytes=67108864;  // optional move/closure cache, separate budget
};

inline DFA determinize(const NFA& a, const DeterminizeOptions& opt={}) {
    validate(a);
    require(opt.max_states>0, "DFA state limit must be positive");
    int n=static_cast<int>(a.adj.size()), k=static_cast<int>(a.alphabet.size());
    // Remove unreachable states before epsilon-SCC preprocessing.
    std::vector<uint8_t> reachable(n,0); std::vector<int> todo{a.start}; reachable[a.start]=1;
    for(size_t i=0;i<todo.size();++i) for(auto e:a.adj[todo[i]])
        if(!reachable[e.to]) { reachable[e.to]=1; todo.push_back(e.to); }
    std::vector<std::vector<int>> eps(n), rev(n);
    for(int u:todo) for(auto e:a.adj[u]) if(e.symbol<0) {
        eps[u].push_back(e.to); rev[e.to].push_back(u);
    }
    // Iterative Kosaraju: long epsilon chains cannot overflow the call stack.
    std::vector<uint8_t> seen(n,0); std::vector<int> finish; finish.reserve(todo.size());
    for(int root:todo) if(!seen[root]) {
        std::vector<std::pair<int,size_t>> st{{root,0}}; seen[root]=1;
        while(!st.empty()) {
            int u=st.back().first; size_t& p=st.back().second;
            if(p==eps[u].size()) { finish.push_back(u); st.pop_back(); }
            else { int v=eps[u][p++]; if(!seen[v]) { seen[v]=1; st.push_back({v,0}); } }
        }
    }
    std::vector<int> component(n,-1); int count=0;
    for(auto it=finish.rbegin();it!=finish.rend();++it) if(component[*it]<0) {
        std::vector<int> st{*it}; component[*it]=count;
        while(!st.empty()) { int u=st.back();st.pop_back();for(int v:rev[u])
            if(component[v]<0) {component[v]=count;st.push_back(v);} }
        ++count;
    }
    size_t words=(static_cast<size_t>(count)+63)/64, bytes=words*sizeof(uint64_t);
    // One accepting mask and two temporary bitsets; map keys are owned only once.
    require(static_cast<size_t>(count)+3 <= opt.max_bitset_bytes/bytes,
            "epsilon-closure bitset budget exceeded; increase --bitset-mib");
    size_t fixed=static_cast<size_t>(count)+3;
    std::vector<std::vector<int>> dag(count); std::vector<int> indeg(count,0);
    for(int u:todo) for(int v:eps[u]) if(component[u]!=component[v])
        dag[component[u]].push_back(component[v]);
    for(auto& row:dag) {
        std::sort(row.begin(),row.end()); row.erase(std::unique(row.begin(),row.end()),row.end());
        for(int v:row) ++indeg[v];
    }
    std::vector<int> topo; topo.reserve(count);
    for(int c=0;c<count;++c) if(!indeg[c]) topo.push_back(c);
    for(size_t i=0;i<topo.size();++i) for(int v:dag[topo[i]]) if(--indeg[v]==0) topo.push_back(v);
    std::vector<Bits> closure; closure.reserve(count);
    for(int c=0;c<count;++c) { closure.emplace_back(words);closure.back().set(c); }
    for(auto it=topo.rbegin();it!=topo.rend();++it) for(int v:dag[*it]) closure[*it].merge(closure[v]);
    Bits finals(words); for(int u:todo) if(a.accept[u]) finals.set(component[u]);
    // Only nonempty (component,symbol) pairs are stored; cache within an explicit budget.
    struct Move { int symbol; std::vector<int> targets; int cache=-1; };
    std::vector<std::vector<Move>> moves(count);
    std::vector<std::vector<std::pair<int,int>>> raw(count);
    for(int u:todo) for(auto e:a.adj[u]) if(e.symbol>=0)
        raw[component[u]].push_back({e.symbol,component[e.to]});
    std::vector<Bits> cache;
    for(int c=0;c<count;++c) {
        auto& row=raw[c]; std::sort(row.begin(),row.end());
        row.erase(std::unique(row.begin(),row.end()),row.end());
        for(auto p:row) {
            if(moves[c].empty() || moves[c].back().symbol!=p.first) moves[c].push_back({p.first,{},-1});
            moves[c].back().targets.push_back(p.second);
        }
        for(auto& m:moves[c]) if(m.targets.size()>1 && cache.size()<opt.max_cache_bytes/bytes) {
            require(cache.size()<static_cast<size_t>(INT32_MAX), "move cache too large");
            m.cache=static_cast<int>(cache.size());cache.emplace_back(words);
            for(int t:m.targets) cache.back().merge(closure[t]);
        }
        std::vector<std::pair<int,int>>().swap(row);
    }
    DFA d; d.alphabet=a.alphabet;
    std::unordered_map<Bits,int,BitsHash> ids;
    ids.max_load_factor(0.7f); ids.reserve(std::min<size_t>(opt.max_states,4096));
    std::vector<const Bits*> states; // unordered_map element references survive rehash
    auto intern=[&](Bits bits) {
        auto it=ids.find(bits); if(it!=ids.end()) return it->second;
        require(states.size()<opt.max_states && states.size()<static_cast<size_t>(INT32_MAX),
                "DFA state limit exceeded; subset construction may be exponential");
        require(states.size()<opt.max_bitset_bytes/bytes-fixed, "DFA subset bitset budget exceeded");
        int id=static_cast<int>(states.size());
        auto p=ids.emplace(std::move(bits),id);
        states.push_back(&p.first->first);
        d.accept.push_back(p.first->first.intersects(finals) ? 1 : 0);
        d.trans.emplace_back(k,-1); return id;
    };
    d.start=intern(closure[component[a.start]]);
    std::vector<int> active;
    for(size_t i=0;i<states.size();++i) {
        active.clear();states[i]->each([&](int c){active.push_back(c);});
        for(int symbol=0;symbol<k;++symbol) {
            Bits target(words);
            for(int c:active) {
                const auto& row=moves[c];
                auto it=std::lower_bound(row.begin(),row.end(),symbol,
                    [](const Move& m,int s){return m.symbol<s;});
                if(it==row.end() || it->symbol!=symbol) continue;
                if(it->cache>=0) target.merge(cache[it->cache]);
                else for(int t:it->targets) target.merge(closure[t]);
            }
            int v=intern(std::move(target)); // may reallocate d.trans; assign afterward
            d.trans[i][symbol]=v;
        }
    }
    return d; // empty subset becomes a total rejecting sink, when reachable
}
} // namespace fa

// END include/core.hpp
#include <iomanip>
#include <sstream>

namespace fa {
// Input limits also prevent corrupt input from triggering unbounded allocations.
constexpr long long INPUT_STATES=1000000, INPUT_EDGES=256000000, INPUT_CELLS=256000000;
inline long long read_integer(std::istream& in, const char* field) {
    std::string s; require(bool(in>>s),std::string("missing ")+field);
    require(s.size()<=20,"integer token too long");
    size_t used=0; long long x=0;
    try { x=std::stoll(s,&used); } catch(...) { throw std::runtime_error(std::string("invalid ")+field); }
    require(used==s.size(),std::string("invalid integer: ")+field);return x;
}
inline int bounded_integer(std::istream& in,long long lo,long long hi,const char* field) {
    long long x=read_integer(in,field);require(x>=lo && x<=hi,std::string("out of range: ")+field);
    return static_cast<int>(x);
}
inline int hex_digit(char c) {
    if(c>='0' && c<='9') return c-'0';
    if(c>='a' && c<='f') return c-'a'+10;
    if(c>='A' && c<='F') return c-'A'+10;
    return -1;
}
inline int byte_token(const std::string& s) {
    require(s.size()==2 && hex_digit(s[0])>=0 && hex_digit(s[1])>=0,"byte must use two hex digits, e.g. 61");
    return hex_digit(s[0])*16+hex_digit(s[1]);
}
inline std::string byte_text(int c) {
    constexpr char digits[]="0123456789ABCDEF";
    std::string s(2,'0');s[0]=digits[c>>4];s[1]=digits[c&15];return s;
}
inline void read_alphabet(std::istream& in,int k,std::vector<int>& alphabet) {
    for(int i=0;i<k;++i) {std::string s;require(bool(in>>s),"missing alphabet byte");alphabet.push_back(byte_token(s));}
    validate_alphabet(alphabet);
}
inline void read_finals(std::istream& in,int n,int f,std::vector<uint8_t>& accept) {
    accept.assign(n,0);
    for(int i=0;i<f;++i) {int u=bounded_integer(in,0,n-1,"final state");require(!accept[u],"duplicate final state");accept[u]=1;}
}
inline void require_end(std::istream& in) {
    std::string extra;require(!(in>>extra),"unexpected trailing input");
    require(!in.bad(),"input read failed");
}
inline NFA read_nfa_body(std::istream& in) {
    int n=bounded_integer(in,1,INPUT_STATES,"NFA n");
    int k=bounded_integer(in,0,256,"alphabet size");
    NFA a;a.start=bounded_integer(in,0,n-1,"start");
    int f=bounded_integer(in,0,n,"final count"),m=bounded_integer(in,0,INPUT_EDGES,"edge count");
    read_alphabet(in,k,a.alphabet);read_finals(in,n,f,a.accept);a.adj.resize(n);
    std::array<int,256> index;index.fill(-1);for(int i=0;i<k;++i)index[a.alphabet[i]]=i;
    for(int i=0;i<m;++i) {
        int u=bounded_integer(in,0,n-1,"edge source"),v=bounded_integer(in,0,n-1,"edge target");
        std::string s;require(bool(in>>s),"missing edge label");int symbol=-1;
        if(s!="eps") {symbol=index[byte_token(s)];require(symbol>=0,"edge byte absent from alphabet");}
        a.adj[u].push_back({v,symbol});
    }
    validate(a);return a;
}
inline DFA read_dfa_body(std::istream& in) {
    int n=bounded_integer(in,1,INPUT_STATES,"DFA n"),k=bounded_integer(in,0,256,"alphabet size");
    require(static_cast<long long>(n)*k<=INPUT_CELLS,"DFA input transition table too large");
    DFA a;a.start=bounded_integer(in,0,n-1,"start");int f=bounded_integer(in,0,n,"final count");
    read_alphabet(in,k,a.alphabet);read_finals(in,n,f,a.accept);
    a.trans.assign(n,std::vector<int>(k));
    for(auto& row:a.trans)for(int& v:row)v=bounded_integer(in,-1,n-1,"DFA target");
    validate(a);return a;
}
inline std::string read_kind(std::istream& in) {
    std::string s;require(bool(in>>s),"missing NFA/DFA header");return s;
}
inline NFA read_nfa(std::istream& in) {
    require(read_kind(in)=="NFA","expected NFA header");NFA a=read_nfa_body(in);require_end(in);return a;
}
inline DFA read_dfa(std::istream& in) {
    require(read_kind(in)=="DFA","expected DFA header");DFA a=read_dfa_body(in);require_end(in);return a;
}
inline NFA read_automaton_as_nfa(std::istream& in) {
    std::string kind=read_kind(in);NFA a;
    if(kind=="NFA")a=read_nfa_body(in);
    else {require(kind=="DFA","expected NFA or DFA header");a=as_nfa(read_dfa_body(in));}
    require_end(in);return a;
}
inline void write_alphabet_finals(std::ostream& out,const std::vector<int>& alphabet,const std::vector<uint8_t>& accept) {
    for(size_t i=0;i<alphabet.size();++i) out<<(i?" ":"")<<byte_text(alphabet[i]);
    out<<'\n';
    bool first=true;for(size_t i=0;i<accept.size();++i)if(accept[i]) {out<<(first?"":" ")<<i;first=false;}out<<'\n';
}
inline void write_nfa(std::ostream& out,const NFA& a) {
    validate(a);size_t m=0;for(auto& row:a.adj)m+=row.size();
    out<<"NFA\n"<<a.adj.size()<<' '<<a.alphabet.size()<<' '<<a.start<<' '
       <<std::count(a.accept.begin(),a.accept.end(),uint8_t(1))<<' '<<m<<'\n';
    write_alphabet_finals(out,a.alphabet,a.accept);
    for(size_t u=0;u<a.adj.size();++u)for(auto e:a.adj[u])
        out<<u<<' '<<e.to<<' '<<(e.symbol<0 ? "eps" : byte_text(a.alphabet[e.symbol]))<<'\n';
}
inline void write_dfa(std::ostream& out,const DFA& a) {
    validate(a);out<<"DFA\n"<<a.trans.size()<<' '<<a.alphabet.size()<<' '<<a.start<<' '
       <<std::count(a.accept.begin(),a.accept.end(),uint8_t(1))<<'\n';
    write_alphabet_finals(out,a.alphabet,a.accept);
    for(auto& row:a.trans) {for(size_t c=0;c<row.size();++c)out<<(c?" ":"")<<row[c];out<<'\n';}
}
} // namespace fa

// END include/io.hpp
#include <functional>
#include <iterator>
#include <map>
#include <set>
namespace fa {
class Arguments {
    std::map<std::string,size_t> values;
public:
    Arguments(int argc,char** argv,std::initializer_list<std::string> allowed) {
        std::set<std::string> names(allowed);
        for(int i=1;i<argc;i+=2) {
            std::string key=argv[i];require(names.count(key)>0,"unknown option: "+key);
            require(i+1<argc,"missing value for "+key);require(!values.count(key),"duplicate option: "+key);
            std::string value=argv[i+1];require(!value.empty(),"empty option value");
            size_t x=0;for(char c:value) {
                require(c>='0' && c<='9',"option must be a nonnegative decimal integer: "+key);
                require(x<=(std::numeric_limits<size_t>::max()-static_cast<unsigned>(c-'0'))/10,"option integer overflow");
                x=x*10+static_cast<unsigned>(c-'0');
            }
            values.emplace(key,x);
        }
    }
    size_t get(const std::string& key,size_t fallback) const {
        auto it=values.find(key);return it==values.end()?fallback:it->second;
    }
    DeterminizeOptions determinize_options() const {
        DeterminizeOptions o;o.max_states=get("--max-states",o.max_states);
        auto mib=[&](const std::string& key,size_t def) {
            size_t x=get(key,def>>20);require(x<=std::numeric_limits<size_t>::max()/(1<<20),"MiB overflow");return x*(1<<20);
        };
        o.max_bitset_bytes=mib("--bitset-mib",o.max_bitset_bytes);
        o.max_cache_bytes=mib("--cache-mib",o.max_cache_bytes);return o;
    }
};
inline std::string read_regex(std::istream& in) {
    // Bounded streaming read rather than an unbounded istreambuf_iterator allocation.
    constexpr size_t limit=1000000;std::string s;char ch;
    while(in.get(ch)) {require(s.size()<limit,"regex input exceeds 1000000 bytes");s+=ch;}
    require(!in.bad(),"input read failed");return s;
}
template<class F> int cli_main(F run) {
    std::ios::sync_with_stdio(false);std::cin.tie(nullptr);
    try {run();require(bool(std::cout),"output write failed");return 0;}
    catch(const std::exception& e) {std::cerr<<"ERROR: "<<e.what()<<'\n';return 1;}
}
} // namespace fa

// END include/cli.hpp
// BEGIN include/minimize.hpp


#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <utility>
#include <vector>

namespace fa {

// Hopcroft minimization. Missing transitions mean rejection, so first add a
// sink when necessary and remove unreachable states. The result is total.
// Time: O(n + k*n*log(n+1)); space: O(k*n+n), including normalization.
inline DFA minimize_dfa(const DFA& input) {
    const DFA dfa = complete_reachable(input);
    const int n = static_cast<int>(dfa.trans.size());
    const int k = static_cast<int>(dfa.alphabet.size());

    int final_count = 0;
    for (const auto value : dfa.accept) final_count += (value != 0);
    if (final_count == 0 || final_count == n) {
        DFA result;
        result.start = 0;
        result.alphabet = dfa.alphabet;
        result.trans.assign(1, std::vector<int>(k, 0));
        result.accept.assign(1, static_cast<std::uint8_t>(final_count != 0));
        return result;
    }

    // CSR inverse transitions. For symbol c, predecessors of q are in
    // predecessor[c][offset[c][q] .. offset[c][q+1]).
    std::vector<std::vector<int>> offset(
        k, std::vector<int>(static_cast<std::size_t>(n) + 1, 0));
    std::vector<std::vector<int>> predecessor(k, std::vector<int>(n));
    for (int c = 0; c < k; ++c) {
        for (int q = 0; q < n; ++q) ++offset[c][dfa.trans[q][c] + 1];
        for (int q = 0; q < n; ++q) offset[c][q + 1] += offset[c][q];
        std::vector<int> cursor = offset[c];
        for (int q = 0; q < n; ++q) {
            predecessor[c][cursor[dfa.trans[q][c]]++] = q;
        }
    }

    struct Block {
        int begin;
        int end;
        std::vector<std::uint8_t> pending;
    };
    std::vector<Block> blocks;
    blocks.reserve(n);  // At most n nonempty blocks; no references can move.
    blocks.push_back({0, n - final_count, std::vector<std::uint8_t>(k, 0)});
    blocks.push_back({n - final_count, n, std::vector<std::uint8_t>(k, 0)});

    // Every block owns an interval of one global permutation. Swapping a
    // marked state to the interval's right end relocates it in O(1), without
    // scanning the other half or retaining oversized per-block allocations.
    std::vector<int> order(n), position(n), belong(n);
    int reject_cursor = 0;
    int accept_cursor = n - final_count;
    for (int q = 0; q < n; ++q) {
        const bool accepting = dfa.accept[q] != 0;
        const int p = accepting ? accept_cursor++ : reject_cursor++;
        order[p] = q;
        position[q] = p;
        belong[q] = accepting ? 1 : 0;
    }

    std::deque<std::pair<int, int>> work;
    const auto enqueue = [&](int block, int symbol) {
        if (!blocks[block].pending[symbol]) {
            blocks[block].pending[symbol] = 1;
            work.emplace_back(block, symbol);
        }
    };
    const int initial = (n - final_count <= final_count) ? 0 : 1;
    for (int c = 0; c < k; ++c) enqueue(initial, c);

    // Each state has exactly one successor for the current symbol, hence it
    // occurs at most once in a splitter's inverse image. No visited bitset or
    // O(n) clearing pass is necessary.
    std::vector<int> marked_head(n, -1), marked_count(n, 0), marked_next(n, -1);
    std::vector<int> touched;
    touched.reserve(n);

    while (!work.empty()) {
        const auto [splitter, symbol] = work.front();
        work.pop_front();
        blocks[splitter].pending[symbol] = 0;
        touched.clear();

        // Capture the entire inverse image BEFORE splitting any block. The
        // splitter itself may be divided below; iterating it during mutation
        // would silently miss states and invalidate Hopcroft's invariant.
        for (int p = blocks[splitter].begin; p < blocks[splitter].end; ++p) {
            const int target = order[p];
            for (int e = offset[symbol][target]; e < offset[symbol][target + 1]; ++e) {
                const int state = predecessor[symbol][e];
                const int block = belong[state];
                if (marked_count[block]++ == 0) touched.push_back(block);
                marked_next[state] = marked_head[block];
                marked_head[block] = state;
            }
        }

        for (const int block : touched) {
            const int count = marked_count[block];
            int state = marked_head[block];
            marked_count[block] = 0;
            marked_head[block] = -1;
            const int old_end = blocks[block].end;
            const int old_size = old_end - blocks[block].begin;
            if (count == old_size) continue;

            const int added = static_cast<int>(blocks.size());
            const int boundary = old_end - count;
            blocks.push_back({boundary, old_end, std::vector<std::uint8_t>(k, 0)});
            int write = old_end;
            while (state != -1) {
                const int next = marked_next[state];
                const int from = position[state];
                const int displaced = order[--write];
                std::swap(order[from], order[write]);
                position[state] = write;
                position[displaced] = from;
                belong[state] = added;
                state = next;
            }
            blocks[block].end = boundary;

            const int smaller = (old_size - count <= count) ? block : added;
            for (int c = 0; c < k; ++c) {
                if (blocks[block].pending[c]) {
                    // An old queued splitter is replaced by both pieces:
                    // its existing entry now names the unmarked piece.
                    enqueue(added, c);
                } else {
                    enqueue(smaller, c);
                }
            }
        }
    }

    // Quotient the stable partition and number states by BFS, following the
    // caller's alphabet order. This gives a deterministic, reachable output.
    DFA result;
    result.start = 0;
    result.alphabet = dfa.alphabet;
    std::vector<int> new_id(blocks.size(), -1), queue;
    queue.reserve(blocks.size());
    const int start_block = belong[dfa.start];
    new_id[start_block] = 0;
    queue.push_back(start_block);
    for (std::size_t i = 0; i < queue.size(); ++i) {
        const int representative = order[blocks[queue[i]].begin];
        result.accept.push_back(static_cast<std::uint8_t>(dfa.accept[representative] != 0));
        std::vector<int> row(k);
        for (int c = 0; c < k; ++c) {
            const int target_block = belong[dfa.trans[representative][c]];
            if (new_id[target_block] == -1) {
                new_id[target_block] = static_cast<int>(queue.size());
                queue.push_back(target_block);
            }
            row[c] = new_id[target_block];
        }
        result.trans.push_back(std::move(row));
    }
    return result;
}

}  // namespace fa

// END include/minimize.hpp
int main(int argc,char** argv) {return fa::cli_main([&] {
    fa::Arguments args(argc,argv,{});
    auto d=fa::minimize_dfa(fa::read_dfa(std::cin));fa::write_dfa(std::cout,d);
});}

// END dfa_minimize.cpp
