// Generated by make_single.py; edit include/ and regenerate.
// BEGIN regex_to_nfa.cpp
// BEGIN include/cli.hpp
// BEGIN include/io.hpp
// BEGIN include/core.hpp
#include <algorithm>
#include <array>
#include <cstdint>
#include <deque>
#include <iostream>
#include <limits>
#include <numeric>
#include <queue>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace fa {
struct Edge { int to; int symbol; }; // symbol=-1: epsilon; otherwise alphabet index
struct NFA {
    int start = 0;
    std::vector<int> alphabet;
    std::vector<std::vector<Edge>> adj;
    std::vector<uint8_t> accept;
};
struct DFA {
    int start = 0;
    std::vector<int> alphabet;
    std::vector<std::vector<int>> trans; // -1 means implicit rejection
    std::vector<uint8_t> accept;
};
inline void require(bool ok, const std::string& message) {
    if (!ok) throw std::runtime_error(message);
}
inline void validate_alphabet(const std::vector<int>& alphabet) {
    std::array<bool,256> seen{};
    for (int c : alphabet) {
        require(c >= 0 && c < 256, "alphabet byte must be in [0,255]");
        require(!seen[c], "duplicate alphabet byte"); seen[c] = true;
    }
}
inline void validate(const NFA& a) {
    validate_alphabet(a.alphabet);
    require(!a.adj.empty() && a.adj.size() <= static_cast<size_t>(INT32_MAX), "invalid NFA state count");
    int n = static_cast<int>(a.adj.size()), k = static_cast<int>(a.alphabet.size());
    require(a.start >= 0 && a.start < n && a.accept.size() == a.adj.size(), "invalid NFA start/finals");
    for (int u=0; u<n; ++u) {
        require(a.accept[u] <= 1, "accept flags must be 0 or 1");
        for (auto e : a.adj[u]) require(e.to>=0 && e.to<n && e.symbol>=-1 && e.symbol<k, "invalid NFA edge");
    }
}
inline void validate(const DFA& a) {
    validate_alphabet(a.alphabet);
    require(!a.trans.empty() && a.trans.size() <= static_cast<size_t>(INT32_MAX), "invalid DFA state count");
    int n = static_cast<int>(a.trans.size());
    require(a.start>=0 && a.start<n && a.accept.size()==a.trans.size(), "invalid DFA start/finals");
    for (int u=0; u<n; ++u) {
        require(a.accept[u]<=1 && a.trans[u].size()==a.alphabet.size(), "invalid DFA row/final");
        for (int v : a.trans[u]) require(v>=-1 && v<n, "invalid DFA transition");
    }
}

// Reachable BFS, with a lazily created rejecting sink. Alphabet order is preserved.
inline DFA complete_reachable(const DFA& a) {
    validate(a);
    int n=static_cast<int>(a.trans.size()), k=static_cast<int>(a.alphabet.size());
    require(n<INT32_MAX, "too many DFA states to add a sink");
    std::vector<int> id(static_cast<size_t>(n)+1,-1), order{a.start};
    id[a.start]=0;
    DFA b; b.alphabet=a.alphabet;
    for (size_t i=0; i<order.size(); ++i) {
        int u=order[i];
        std::vector<int> row(k);
        for (int c=0;c<k;++c) {
            int v=(u==n || a.trans[u][c]<0) ? n : a.trans[u][c];
            if (id[v]<0) { id[v]=static_cast<int>(order.size()); order.push_back(v); }
            row[c]=id[v];
        }
        b.trans.push_back(std::move(row));
        b.accept.push_back(u==n ? 0 : a.accept[u]);
    }
    return b;
}
inline NFA as_nfa(const DFA& a) {
    validate(a);
    NFA b; b.start=a.start; b.alphabet=a.alphabet; b.accept=a.accept;
    b.adj.resize(a.trans.size());
    for (size_t u=0;u<a.trans.size();++u)
        for (size_t c=0;c<a.alphabet.size();++c)
            if (a.trans[u][c]>=0) b.adj[u].push_back({a.trans[u][c],static_cast<int>(c)});
    return b;
}

// Runtime-sized bitset: no fixed MAXN and no vector<bool> proxy overhead.
struct Bits {
    std::vector<uint64_t> w;
    Bits() = default;
    explicit Bits(size_t words) : w(words,0) {}
    void set(int i) { w[static_cast<size_t>(i)>>6] |= uint64_t(1)<<(i&63); }
    void merge(const Bits& b) { for(size_t i=0;i<w.size();++i) w[i]|=b.w[i]; }
    bool intersects(const Bits& b) const {
        for(size_t i=0;i<w.size();++i) if(w[i]&b.w[i]) return true;
        return false;
    }
    bool operator==(const Bits& b) const { return w==b.w; }
    template<class F> void each(F f) const {
        for(size_t i=0;i<w.size();++i) {
            uint64_t x=w[i];
            while(x) {
                unsigned bit=static_cast<unsigned>(__builtin_ctzll(x)); // x is nonzero
                f(static_cast<int>(i*64+bit)); x&=x-1;
            }
        }
    }
};
struct BitsHash {
    size_t operator()(const Bits& b) const noexcept {
        uint64_t h=0x243f6a8885a308d3ULL;
        for(uint64_t x : b.w) {
            x+=0x9e3779b97f4a7c15ULL; x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;
            x=(x^(x>>27))*0x94d049bb133111ebULL; x^=x>>31;
            h^=x+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);
        }
        return static_cast<size_t>(h);
    }
};
struct DeterminizeOptions {
    size_t max_states=200000;
    size_t max_bitset_bytes=268435456; // epsilon closures + subset keys + temporary words
    size_t max_cache_bytes=67108864;  // optional move/closure cache, separate budget
};

inline DFA determinize(const NFA& a, const DeterminizeOptions& opt={}) {
    validate(a);
    require(opt.max_states>0, "DFA state limit must be positive");
    int n=static_cast<int>(a.adj.size()), k=static_cast<int>(a.alphabet.size());
    // Remove unreachable states before epsilon-SCC preprocessing.
    std::vector<uint8_t> reachable(n,0); std::vector<int> todo{a.start}; reachable[a.start]=1;
    for(size_t i=0;i<todo.size();++i) for(auto e:a.adj[todo[i]])
        if(!reachable[e.to]) { reachable[e.to]=1; todo.push_back(e.to); }
    std::vector<std::vector<int>> eps(n), rev(n);
    for(int u:todo) for(auto e:a.adj[u]) if(e.symbol<0) {
        eps[u].push_back(e.to); rev[e.to].push_back(u);
    }
    // Iterative Kosaraju: long epsilon chains cannot overflow the call stack.
    std::vector<uint8_t> seen(n,0); std::vector<int> finish; finish.reserve(todo.size());
    for(int root:todo) if(!seen[root]) {
        std::vector<std::pair<int,size_t>> st{{root,0}}; seen[root]=1;
        while(!st.empty()) {
            int u=st.back().first; size_t& p=st.back().second;
            if(p==eps[u].size()) { finish.push_back(u); st.pop_back(); }
            else { int v=eps[u][p++]; if(!seen[v]) { seen[v]=1; st.push_back({v,0}); } }
        }
    }
    std::vector<int> component(n,-1); int count=0;
    for(auto it=finish.rbegin();it!=finish.rend();++it) if(component[*it]<0) {
        std::vector<int> st{*it}; component[*it]=count;
        while(!st.empty()) { int u=st.back();st.pop_back();for(int v:rev[u])
            if(component[v]<0) {component[v]=count;st.push_back(v);} }
        ++count;
    }
    size_t words=(static_cast<size_t>(count)+63)/64, bytes=words*sizeof(uint64_t);
    // One accepting mask and two temporary bitsets; map keys are owned only once.
    require(static_cast<size_t>(count)+3 <= opt.max_bitset_bytes/bytes,
            "epsilon-closure bitset budget exceeded; increase --bitset-mib");
    size_t fixed=static_cast<size_t>(count)+3;
    std::vector<std::vector<int>> dag(count); std::vector<int> indeg(count,0);
    for(int u:todo) for(int v:eps[u]) if(component[u]!=component[v])
        dag[component[u]].push_back(component[v]);
    for(auto& row:dag) {
        std::sort(row.begin(),row.end()); row.erase(std::unique(row.begin(),row.end()),row.end());
        for(int v:row) ++indeg[v];
    }
    std::vector<int> topo; topo.reserve(count);
    for(int c=0;c<count;++c) if(!indeg[c]) topo.push_back(c);
    for(size_t i=0;i<topo.size();++i) for(int v:dag[topo[i]]) if(--indeg[v]==0) topo.push_back(v);
    std::vector<Bits> closure; closure.reserve(count);
    for(int c=0;c<count;++c) { closure.emplace_back(words);closure.back().set(c); }
    for(auto it=topo.rbegin();it!=topo.rend();++it) for(int v:dag[*it]) closure[*it].merge(closure[v]);
    Bits finals(words); for(int u:todo) if(a.accept[u]) finals.set(component[u]);
    // Only nonempty (component,symbol) pairs are stored; cache within an explicit budget.
    struct Move { int symbol; std::vector<int> targets; int cache=-1; };
    std::vector<std::vector<Move>> moves(count);
    std::vector<std::vector<std::pair<int,int>>> raw(count);
    for(int u:todo) for(auto e:a.adj[u]) if(e.symbol>=0)
        raw[component[u]].push_back({e.symbol,component[e.to]});
    std::vector<Bits> cache;
    for(int c=0;c<count;++c) {
        auto& row=raw[c]; std::sort(row.begin(),row.end());
        row.erase(std::unique(row.begin(),row.end()),row.end());
        for(auto p:row) {
            if(moves[c].empty() || moves[c].back().symbol!=p.first) moves[c].push_back({p.first,{},-1});
            moves[c].back().targets.push_back(p.second);
        }
        for(auto& m:moves[c]) if(m.targets.size()>1 && cache.size()<opt.max_cache_bytes/bytes) {
            require(cache.size()<static_cast<size_t>(INT32_MAX), "move cache too large");
            m.cache=static_cast<int>(cache.size());cache.emplace_back(words);
            for(int t:m.targets) cache.back().merge(closure[t]);
        }
        std::vector<std::pair<int,int>>().swap(row);
    }
    DFA d; d.alphabet=a.alphabet;
    std::unordered_map<Bits,int,BitsHash> ids;
    ids.max_load_factor(0.7f); ids.reserve(std::min<size_t>(opt.max_states,4096));
    std::vector<const Bits*> states; // unordered_map element references survive rehash
    auto intern=[&](Bits bits) {
        auto it=ids.find(bits); if(it!=ids.end()) return it->second;
        require(states.size()<opt.max_states && states.size()<static_cast<size_t>(INT32_MAX),
                "DFA state limit exceeded; subset construction may be exponential");
        require(states.size()<opt.max_bitset_bytes/bytes-fixed, "DFA subset bitset budget exceeded");
        int id=static_cast<int>(states.size());
        auto p=ids.emplace(std::move(bits),id);
        states.push_back(&p.first->first);
        d.accept.push_back(p.first->first.intersects(finals) ? 1 : 0);
        d.trans.emplace_back(k,-1); return id;
    };
    d.start=intern(closure[component[a.start]]);
    std::vector<int> active;
    for(size_t i=0;i<states.size();++i) {
        active.clear();states[i]->each([&](int c){active.push_back(c);});
        for(int symbol=0;symbol<k;++symbol) {
            Bits target(words);
            for(int c:active) {
                const auto& row=moves[c];
                auto it=std::lower_bound(row.begin(),row.end(),symbol,
                    [](const Move& m,int s){return m.symbol<s;});
                if(it==row.end() || it->symbol!=symbol) continue;
                if(it->cache>=0) target.merge(cache[it->cache]);
                else for(int t:it->targets) target.merge(closure[t]);
            }
            int v=intern(std::move(target)); // may reallocate d.trans; assign afterward
            d.trans[i][symbol]=v;
        }
    }
    return d; // empty subset becomes a total rejecting sink, when reachable
}
} // namespace fa

// END include/core.hpp
#include <iomanip>
#include <sstream>

namespace fa {
// Input limits also prevent corrupt input from triggering unbounded allocations.
constexpr long long INPUT_STATES=1000000, INPUT_EDGES=256000000, INPUT_CELLS=256000000;
inline long long read_integer(std::istream& in, const char* field) {
    std::string s; require(bool(in>>s),std::string("missing ")+field);
    require(s.size()<=20,"integer token too long");
    size_t used=0; long long x=0;
    try { x=std::stoll(s,&used); } catch(...) { throw std::runtime_error(std::string("invalid ")+field); }
    require(used==s.size(),std::string("invalid integer: ")+field);return x;
}
inline int bounded_integer(std::istream& in,long long lo,long long hi,const char* field) {
    long long x=read_integer(in,field);require(x>=lo && x<=hi,std::string("out of range: ")+field);
    return static_cast<int>(x);
}
inline int hex_digit(char c) {
    if(c>='0' && c<='9') return c-'0';
    if(c>='a' && c<='f') return c-'a'+10;
    if(c>='A' && c<='F') return c-'A'+10;
    return -1;
}
inline int byte_token(const std::string& s) {
    require(s.size()==2 && hex_digit(s[0])>=0 && hex_digit(s[1])>=0,"byte must use two hex digits, e.g. 61");
    return hex_digit(s[0])*16+hex_digit(s[1]);
}
inline std::string byte_text(int c) {
    constexpr char digits[]="0123456789ABCDEF";
    std::string s(2,'0');s[0]=digits[c>>4];s[1]=digits[c&15];return s;
}
inline void read_alphabet(std::istream& in,int k,std::vector<int>& alphabet) {
    for(int i=0;i<k;++i) {std::string s;require(bool(in>>s),"missing alphabet byte");alphabet.push_back(byte_token(s));}
    validate_alphabet(alphabet);
}
inline void read_finals(std::istream& in,int n,int f,std::vector<uint8_t>& accept) {
    accept.assign(n,0);
    for(int i=0;i<f;++i) {int u=bounded_integer(in,0,n-1,"final state");require(!accept[u],"duplicate final state");accept[u]=1;}
}
inline void require_end(std::istream& in) {
    std::string extra;require(!(in>>extra),"unexpected trailing input");
    require(!in.bad(),"input read failed");
}
inline NFA read_nfa_body(std::istream& in) {
    int n=bounded_integer(in,1,INPUT_STATES,"NFA n");
    int k=bounded_integer(in,0,256,"alphabet size");
    NFA a;a.start=bounded_integer(in,0,n-1,"start");
    int f=bounded_integer(in,0,n,"final count"),m=bounded_integer(in,0,INPUT_EDGES,"edge count");
    read_alphabet(in,k,a.alphabet);read_finals(in,n,f,a.accept);a.adj.resize(n);
    std::array<int,256> index;index.fill(-1);for(int i=0;i<k;++i)index[a.alphabet[i]]=i;
    for(int i=0;i<m;++i) {
        int u=bounded_integer(in,0,n-1,"edge source"),v=bounded_integer(in,0,n-1,"edge target");
        std::string s;require(bool(in>>s),"missing edge label");int symbol=-1;
        if(s!="eps") {symbol=index[byte_token(s)];require(symbol>=0,"edge byte absent from alphabet");}
        a.adj[u].push_back({v,symbol});
    }
    validate(a);return a;
}
inline DFA read_dfa_body(std::istream& in) {
    int n=bounded_integer(in,1,INPUT_STATES,"DFA n"),k=bounded_integer(in,0,256,"alphabet size");
    require(static_cast<long long>(n)*k<=INPUT_CELLS,"DFA input transition table too large");
    DFA a;a.start=bounded_integer(in,0,n-1,"start");int f=bounded_integer(in,0,n,"final count");
    read_alphabet(in,k,a.alphabet);read_finals(in,n,f,a.accept);
    a.trans.assign(n,std::vector<int>(k));
    for(auto& row:a.trans)for(int& v:row)v=bounded_integer(in,-1,n-1,"DFA target");
    validate(a);return a;
}
inline std::string read_kind(std::istream& in) {
    std::string s;require(bool(in>>s),"missing NFA/DFA header");return s;
}
inline NFA read_nfa(std::istream& in) {
    require(read_kind(in)=="NFA","expected NFA header");NFA a=read_nfa_body(in);require_end(in);return a;
}
inline DFA read_dfa(std::istream& in) {
    require(read_kind(in)=="DFA","expected DFA header");DFA a=read_dfa_body(in);require_end(in);return a;
}
inline NFA read_automaton_as_nfa(std::istream& in) {
    std::string kind=read_kind(in);NFA a;
    if(kind=="NFA")a=read_nfa_body(in);
    else {require(kind=="DFA","expected NFA or DFA header");a=as_nfa(read_dfa_body(in));}
    require_end(in);return a;
}
inline void write_alphabet_finals(std::ostream& out,const std::vector<int>& alphabet,const std::vector<uint8_t>& accept) {
    for(size_t i=0;i<alphabet.size();++i) out<<(i?" ":"")<<byte_text(alphabet[i]);
    out<<'\n';
    bool first=true;for(size_t i=0;i<accept.size();++i)if(accept[i]) {out<<(first?"":" ")<<i;first=false;}out<<'\n';
}
inline void write_nfa(std::ostream& out,const NFA& a) {
    validate(a);size_t m=0;for(auto& row:a.adj)m+=row.size();
    out<<"NFA\n"<<a.adj.size()<<' '<<a.alphabet.size()<<' '<<a.start<<' '
       <<std::count(a.accept.begin(),a.accept.end(),uint8_t(1))<<' '<<m<<'\n';
    write_alphabet_finals(out,a.alphabet,a.accept);
    for(size_t u=0;u<a.adj.size();++u)for(auto e:a.adj[u])
        out<<u<<' '<<e.to<<' '<<(e.symbol<0 ? "eps" : byte_text(a.alphabet[e.symbol]))<<'\n';
}
inline void write_dfa(std::ostream& out,const DFA& a) {
    validate(a);out<<"DFA\n"<<a.trans.size()<<' '<<a.alphabet.size()<<' '<<a.start<<' '
       <<std::count(a.accept.begin(),a.accept.end(),uint8_t(1))<<'\n';
    write_alphabet_finals(out,a.alphabet,a.accept);
    for(auto& row:a.trans) {for(size_t c=0;c<row.size();++c)out<<(c?" ":"")<<row[c];out<<'\n';}
}
} // namespace fa

// END include/io.hpp
#include <functional>
#include <iterator>
#include <map>
#include <set>
namespace fa {
class Arguments {
    std::map<std::string,size_t> values;
public:
    Arguments(int argc,char** argv,std::initializer_list<std::string> allowed) {
        std::set<std::string> names(allowed);
        for(int i=1;i<argc;i+=2) {
            std::string key=argv[i];require(names.count(key)>0,"unknown option: "+key);
            require(i+1<argc,"missing value for "+key);require(!values.count(key),"duplicate option: "+key);
            std::string value=argv[i+1];require(!value.empty(),"empty option value");
            size_t x=0;for(char c:value) {
                require(c>='0' && c<='9',"option must be a nonnegative decimal integer: "+key);
                require(x<=(std::numeric_limits<size_t>::max()-static_cast<unsigned>(c-'0'))/10,"option integer overflow");
                x=x*10+static_cast<unsigned>(c-'0');
            }
            values.emplace(key,x);
        }
    }
    size_t get(const std::string& key,size_t fallback) const {
        auto it=values.find(key);return it==values.end()?fallback:it->second;
    }
    DeterminizeOptions determinize_options() const {
        DeterminizeOptions o;o.max_states=get("--max-states",o.max_states);
        auto mib=[&](const std::string& key,size_t def) {
            size_t x=get(key,def>>20);require(x<=std::numeric_limits<size_t>::max()/(1<<20),"MiB overflow");return x*(1<<20);
        };
        o.max_bitset_bytes=mib("--bitset-mib",o.max_bitset_bytes);
        o.max_cache_bytes=mib("--cache-mib",o.max_cache_bytes);return o;
    }
};
inline std::string read_regex(std::istream& in) {
    // Bounded streaming read rather than an unbounded istreambuf_iterator allocation.
    constexpr size_t limit=1000000;std::string s;char ch;
    while(in.get(ch)) {require(s.size()<limit,"regex input exceeds 1000000 bytes");s+=ch;}
    require(!in.bad(),"input read failed");return s;
}
template<class F> int cli_main(F run) {
    std::ios::sync_with_stdio(false);std::cin.tie(nullptr);
    try {run();require(bool(std::cout),"output write failed");return 0;}
    catch(const std::exception& e) {std::cerr<<"ERROR: "<<e.what()<<'\n';return 1;}
}
} // namespace fa

// END include/cli.hpp
// BEGIN include/regex.hpp

#include <algorithm>
#include <array>
#include <cstdint>
#include <functional>
#include <limits>
#include <queue>
#include <stdexcept>
#include <string>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace fa {
namespace regex_detail {

inline bool space(unsigned char c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v';
}
inline int hex(unsigned char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}
inline std::string escaped_byte(unsigned char c) {
    if (c <= 32 || c >= 127) {
        constexpr char h[] = "0123456789ABCDEF";
        return std::string("\\x") + h[c >> 4] + h[c & 15];
    }
    const std::string reserved = "\\.|*+?()@#";
    if (reserved.find(static_cast<char>(c)) != std::string::npos)
        return std::string("\\") + static_cast<char>(c);
    return std::string(1, static_cast<char>(c));
}

} // namespace regex_detail

// Byte regular expressions: implicit concatenation or '.', '|', '*', '+', '?',
// parentheses, @ (epsilon), # (empty language), \xHH and escaped literal bytes.
// ASCII whitespace is ignored unless escaped. Brackets and anchors are literals;
// character classes, wildcard dots and bounded repetitions are not implemented.
inline NFA regex_to_nfa(const std::string& expression, std::size_t max_states = 1000000) {
    struct Fragment { int first, last; };
    NFA result;
    std::array<int, 256> alphabet_index;
    alphabet_index.fill(-1);
    std::vector<Fragment> values;
    std::vector<char> operators;
    bool need_operand = true;
    bool saw_token = false;

    auto state = [&]() -> int {
        if (result.adj.size() >= max_states ||
            result.adj.size() >= static_cast<std::size_t>(std::numeric_limits<int>::max()))
            throw std::runtime_error("regex_to_nfa: state limit exceeded");
        int id = static_cast<int>(result.adj.size());
        result.adj.emplace_back();
        result.accept.push_back(0);
        return id;
    };
    auto edge = [&](int from, int to, int symbol) {
        result.adj[from].push_back(Edge{to, symbol});
    };
    auto reduce = [&]() {
        if (operators.empty() || operators.back() == '(' || values.size() < 2)
            throw std::invalid_argument("regex_to_nfa: missing operand");
        char op = operators.back(); operators.pop_back();
        Fragment b = values.back(); values.pop_back();
        Fragment a = values.back(); values.pop_back();
        if (op == '.') {
            edge(a.last, b.first, -1);
            values.push_back({a.first, b.last});
        } else {
            int first = state(), last = state();
            edge(first, a.first, -1); edge(first, b.first, -1);
            edge(a.last, last, -1); edge(b.last, last, -1);
            values.push_back({first, last});
        }
    };
    auto binary = [&](char op) {
        const int precedence = op == '.' ? 2 : 1;
        while (!operators.empty() && operators.back() != '(' &&
               (operators.back() == '.' ? 2 : 1) >= precedence) reduce();
        operators.push_back(op);
        need_operand = true;
    };

    for (std::size_t p = 0; p < expression.size(); ++p) {
        unsigned char c = static_cast<unsigned char>(expression[p]);
        if (regex_detail::space(c)) continue;
        saw_token = true;
        bool literal = false;
        if (c == '\\') {
            if (++p == expression.size())
                throw std::invalid_argument("regex_to_nfa: trailing backslash");
            c = static_cast<unsigned char>(expression[p]);
            if (c == 'x') {
                if (expression.size() - p < 3 ||
                    regex_detail::hex(static_cast<unsigned char>(expression[p + 1])) < 0 ||
                    regex_detail::hex(static_cast<unsigned char>(expression[p + 2])) < 0)
                    throw std::invalid_argument("regex_to_nfa: expected two hex digits after \\x");
                c = static_cast<unsigned char>(
                    regex_detail::hex(static_cast<unsigned char>(expression[p + 1])) * 16 +
                    regex_detail::hex(static_cast<unsigned char>(expression[p + 2])));
                p += 2;
            }
            literal = true;
        }
        if (!literal && c == '(') {
            if (!need_operand) binary('.');
            operators.push_back('(');
            need_operand = true;
        } else if (!literal && c == ')') {
            if (need_operand) throw std::invalid_argument("regex_to_nfa: empty group or missing operand");
            while (!operators.empty() && operators.back() != '(') reduce();
            if (operators.empty()) throw std::invalid_argument("regex_to_nfa: unmatched closing parenthesis");
            operators.pop_back();
            need_operand = false;
        } else if (!literal && (c == '.' || c == '|')) {
            if (need_operand) throw std::invalid_argument("regex_to_nfa: missing left operand");
            binary(static_cast<char>(c));
        } else if (!literal && (c == '*' || c == '+' || c == '?')) {
            if (need_operand || values.empty())
                throw std::invalid_argument("regex_to_nfa: postfix operator has no operand");
            Fragment a = values.back(); values.pop_back();
            int first = state(), last = state();
            edge(first, a.first, -1); edge(a.last, last, -1);
            if (c != '+') edge(first, last, -1);
            if (c != '?') edge(a.last, a.first, -1);
            values.push_back({first, last});
        } else {
            if (!need_operand) binary('.');
            int first = state(), last = state();
            if (!literal && c == '@') edge(first, last, -1);
            else if (literal || c != '#') {
                int& index = alphabet_index[c];
                if (index < 0) {
                    index = static_cast<int>(result.alphabet.size());
                    result.alphabet.push_back(c);
                }
                edge(first, last, index);
            }
            values.push_back({first, last});
            need_operand = false;
        }
    }
    if (!saw_token) throw std::invalid_argument("regex_to_nfa: empty expression; use @ for epsilon");
    if (need_operand) throw std::invalid_argument("regex_to_nfa: missing right operand");
    while (!operators.empty()) {
        if (operators.back() == '(')
            throw std::invalid_argument("regex_to_nfa: unmatched opening parenthesis");
        reduce();
    }
    if (values.size() != 1) throw std::invalid_argument("regex_to_nfa: malformed expression");
    result.start = values.back().first;
    result.accept[values.back().last] = 1;
    return result;
}

namespace regex_detail {

// Interning shares repeated subexpressions without copying their expanded text.
// Lengths saturate at max_output + 1; only the final expression is serialized.
class Expressions {
    enum Kind : unsigned char { Empty, Epsilon, Literal, Union, Concat, Star };
    struct Node { Kind kind; int a, b; std::size_t length; };
    struct Key {
        Kind kind; int a, b;
        bool operator==(const Key& other) const {
            return kind == other.kind && a == other.a && b == other.b;
        }
    };
    struct Hash {
        std::size_t operator()(const Key& key) const {
            std::size_t h = static_cast<std::size_t>(key.kind);
            h ^= std::hash<int>{}(key.a) + std::size_t(0x9e3779b9U) + (h << 6) + (h >> 2);
            h ^= std::hash<int>{}(key.b) + std::size_t(0x9e3779b9U) + (h << 6) + (h >> 2);
            return h;
        }
    };
    std::vector<Node> nodes_;
    std::unordered_map<Key, int, Hash> intern_;
    std::size_t max_nodes_, max_output_, cap_;

    std::size_t sum(std::size_t a, std::size_t b) const {
        return a >= cap_ || b >= cap_ - a ? cap_ : a + b;
    }
    int precedence(int id) const {
        Kind k = nodes_[id].kind;
        return k == Union ? 1 : k == Concat ? 2 : k == Star ? 3 : 4;
    }
    std::size_t operand_length(int id, int parent_precedence) const {
        return sum(nodes_[id].length, precedence(id) < parent_precedence ? 2 : 0);
    }
    int make(Kind kind, int a, int b, std::size_t length) {
        Key key{kind, a, b};
        auto found = intern_.find(key);
        if (found != intern_.end()) return found->second;
        if (nodes_.size() >= max_nodes_ ||
            nodes_.size() >= static_cast<std::size_t>(std::numeric_limits<int>::max()))
            throw std::runtime_error("nfa_to_regex: expression DAG node limit exceeded");
        int id = static_cast<int>(nodes_.size());
        nodes_.push_back({kind, a, b, length});
        intern_.emplace(key, id);
        return id;
    }
public:
    Expressions(std::size_t max_nodes, std::size_t max_output)
        : max_nodes_(max_nodes), max_output_(max_output),
          cap_(max_output == std::numeric_limits<std::size_t>::max() ? max_output : max_output + 1) {
        make(Empty, -1, -1, 1);   // ID 0
        make(Epsilon, -1, -1, 1); // ID 1
    }
    int literal(unsigned char c) {
        return make(Literal, c, -1, escaped_byte(c).size());
    }
    int unite(int a, int b) {
        if (a == 0) return b;
        if (b == 0 || a == b) return a;
        if (a > b) std::swap(a, b);
        return make(Union, a, b, sum(sum(nodes_[a].length, nodes_[b].length), 1));
    }
    int concat(int a, int b) {
        if (a == 0 || b == 0) return 0;
        if (a == 1) return b;
        if (b == 1) return a;
        return make(Concat, a, b, sum(operand_length(a, 2), operand_length(b, 2)));
    }
    int star(int a) {
        if (a == 0 || a == 1) return 1;
        if (nodes_[a].kind == Star) return a;
        return make(Star, a, -1, sum(operand_length(a, 3), 1));
    }
    std::string serialize(int root) const {
        if (nodes_[root].length > max_output_ ||
            nodes_[root].length > std::string().max_size())
            throw std::runtime_error("nfa_to_regex: expanded expression output limit exceeded");
        struct Task { int id; int parent_precedence; char token; };
        std::vector<Task> stack{{root, 0, 0}};
        std::string output;
        output.reserve(nodes_[root].length);
        auto emit = [&](const std::string& text) {
            if (text.size() > max_output_ - output.size())
                throw std::runtime_error("nfa_to_regex: expanded expression output limit exceeded");
            output += text;
        };
        while (!stack.empty()) {
            Task task = stack.back(); stack.pop_back();
            if (task.id < 0) { emit(std::string(1, task.token)); continue; }
            const Node& node = nodes_[task.id];
            bool parentheses = precedence(task.id) < task.parent_precedence;
            if (parentheses) stack.push_back({-1, 0, ')'});
            switch (node.kind) {
            case Empty: stack.push_back({-1, 0, '#'}); break;
            case Epsilon: stack.push_back({-1, 0, '@'}); break;
            case Literal: emit(escaped_byte(static_cast<unsigned char>(node.a))); break;
            case Union:
                stack.push_back({node.b, 1, 0});
                stack.push_back({-1, 0, '|'});
                stack.push_back({node.a, 1, 0});
                break;
            case Concat:
                stack.push_back({node.b, 2, 0});
                stack.push_back({node.a, 2, 0});
                break;
            case Star:
                stack.push_back({-1, 0, '*'});
                stack.push_back({node.a, 3, 0});
                break;
            }
            if (parentheses) stack.push_back({-1, 0, '('});
        }
        return output;
    }
};

} // namespace regex_detail

// Sparse GNFA elimination. max_nodes bounds both interned expression nodes and
// simultaneously stored GNFA edges (separately); max_output bounds output bytes.
// Resource-limit exceptions never return a partial/truncated regular expression.
inline std::string nfa_to_regex(const NFA& input, std::size_t max_nodes = 1000000,
                                std::size_t max_output = 1000000) {
    validate(input);
    regex_detail::Expressions expressions(max_nodes, max_output);
    const int n = static_cast<int>(input.adj.size());
    std::vector<std::vector<int>> reverse(n);
    for (int u = 0; u < n; ++u)
        for (const Edge& edge : input.adj[u]) reverse[edge.to].push_back(u);
    std::vector<unsigned char> reachable(n, 0), productive(n, 0);
    std::vector<int> queue;
    reachable[input.start] = 1;
    queue.push_back(input.start);
    for (std::size_t p = 0; p < queue.size(); ++p)
        for (const Edge& edge : input.adj[queue[p]])
            if (!reachable[edge.to]) { reachable[edge.to] = 1; queue.push_back(edge.to); }
    queue.clear();
    for (int u = 0; u < n; ++u)
        if (input.accept[u]) { productive[u] = 1; queue.push_back(u); }
    for (std::size_t p = 0; p < queue.size(); ++p)
        for (int u : reverse[queue[p]])
            if (!productive[u]) { productive[u] = 1; queue.push_back(u); }
    if (!productive[input.start]) return expressions.serialize(0);

    std::vector<int> remap(n, -1);
    int count = 0;
    for (int u = 0; u < n; ++u)
        if (reachable[u] && productive[u]) {
            if (count >= std::numeric_limits<int>::max() - 2)
                throw std::runtime_error("nfa_to_regex: too many states");
            remap[u] = count++;
        }
    const int start = count, finish = count + 1;
    std::vector<std::unordered_map<int, int>> outgoing(count + 2);
    std::vector<std::unordered_set<int>> incoming(count + 2);
    std::vector<unsigned char> alive(count, 1), dirty(count, 0);
    std::vector<int> touched;
    std::size_t edge_count = 0;
    auto mark = [&](int u) {
        if (u < count && alive[u] && !dirty[u]) { dirty[u] = 1; touched.push_back(u); }
    };
    auto add_edge = [&](int u, int v, int expression) {
        if (expression == 0) return;
        auto found = outgoing[u].find(v);
        if (found != outgoing[u].end()) {
            found->second = expressions.unite(found->second, expression);
        } else {
            if (edge_count >= max_nodes)
                throw std::runtime_error("nfa_to_regex: sparse GNFA edge limit exceeded");
            outgoing[u].emplace(v, expression);
            incoming[v].insert(u);
            ++edge_count;
            mark(u); mark(v);
        }
    };
    for (int u = 0; u < n; ++u) if (remap[u] >= 0) {
        for (const Edge& edge : input.adj[u]) if (remap[edge.to] >= 0) {
            int label = edge.symbol < 0 ? 1 : expressions.literal(
                static_cast<unsigned char>(input.alphabet[edge.symbol]));
            add_edge(remap[u], remap[edge.to], label);
        }
        if (input.accept[u]) add_edge(remap[u], finish, 1);
    }
    add_edge(start, remap[input.start], 1);

    // Minimize the number of predecessor/successor pairs created by elimination.
    // Lazy versioning and periodic rebuilds bound stale priority-queue entries.
    using Entry = std::tuple<std::uint64_t, std::uint64_t, int, std::uint64_t>;
    std::priority_queue<Entry, std::vector<Entry>, std::greater<Entry>> heap;
    std::vector<std::uint64_t> version(count, 0);
    auto push_score = [&](int u) {
        std::uint64_t self = outgoing[u].count(u);
        std::uint64_t a = incoming[u].size() - self;
        std::uint64_t b = outgoing[u].size() - self;
        heap.emplace(a * b, a + b, u, ++version[u]);
    };
    for (int u = 0; u < count; ++u) push_score(u);
    for (int u : touched) dirty[u] = 0;
    touched.clear();
    for (int remaining = count; remaining > 0; --remaining) {
        while (!heap.empty() &&
               (!alive[std::get<2>(heap.top())] ||
                std::get<3>(heap.top()) != version[std::get<2>(heap.top())])) heap.pop();
        if (heap.empty()) throw std::logic_error("nfa_to_regex: invalid elimination queue");
        int k = std::get<2>(heap.top()); heap.pop();
        alive[k] = 0;
        std::vector<std::pair<int, int>> pred, succ;
        for (int u : incoming[k]) if (u != k) pred.emplace_back(u, outgoing[u].at(k));
        for (const auto& edge : outgoing[k]) if (edge.first != k) succ.push_back(edge);
        std::sort(pred.begin(), pred.end());
        std::sort(succ.begin(), succ.end());
        auto loop = outgoing[k].find(k);
        int repeat = expressions.star(loop == outgoing[k].end() ? 0 : loop->second);
        // All labels are snapshots: inserting new edges cannot invalidate these.
        for (const auto& a : pred) {
            int prefix = expressions.concat(a.second, repeat);
            for (const auto& b : succ)
                add_edge(a.first, b.first, expressions.concat(prefix, b.second));
        }
        for (int u : incoming[k]) if (u != k) {
            outgoing[u].erase(k); --edge_count; mark(u);
        }
        for (const auto& edge : outgoing[k]) {
            incoming[edge.first].erase(k); --edge_count; mark(edge.first);
        }
        incoming[k].clear(); outgoing[k].clear();
        for (int u : touched) { dirty[u] = 0; if (alive[u]) push_score(u); }
        touched.clear();
        if (heap.size() > std::size_t(remaining) * 8 + 1024) {
            decltype(heap) fresh;
            heap.swap(fresh);
            for (int u = 0; u < count; ++u) if (alive[u]) push_score(u);
        }
    }
    auto answer = outgoing[start].find(finish);
    return expressions.serialize(answer == outgoing[start].end() ? 0 : answer->second);
}

} // namespace fa

// END include/regex.hpp
int main(int argc,char** argv) {return fa::cli_main([&] {
    fa::Arguments args(argc,argv,{"--max-states"});
    auto a=fa::regex_to_nfa(fa::read_regex(std::cin),args.get("--max-states",1000000));
    fa::write_nfa(std::cout,a);
});}

// END regex_to_nfa.cpp
